### ISSUE TITLE
JPG Decoder not correctly decoding. height is always 0

### ISSUE THREAD

**Issue by moefear85** [Bodmer/TJpg_Decoder#34]
I've tried several images from the web, as well as frames captured directly with the esp32-cam module, directly in jpeg format (no conversion). All images have dimensions 320x240. Yet TJpg_Decoder always returns 320 for the width correctly, but always returns 0 for the height. The images are always noise, with general features recognizable that resemble the original image.

P.S: I'm using esp-idf directly. I included a CMakeLists.txt file in the src folder to make it directly usable as a component. I also did the same for tft_espi (which itself works great).

I've tried with master & with 1.0.2

**Comment by Bodmer** [comment]
It sounds like a byte swap problem for the rendering. Try putting 
tft.setSwapBytes(true); // Also try false
In your sketch setup() .

Does a sketch example work OK?

Provide an example image.

I  am working away so it will be 2 weeks before I can investigate.

**Comment by Bodmer** [comment]
I assume this has been resolved. I am not able to help without further information.

**Comment by moefear85** [comment]
Hi Sorry it took so long to respond... I should have mentioned earlier that I already tried setSwapBytes() both with true and false, as well as so many other possibilities that I've exhausted. Is really noone else experiencing anything similar?

No offense, I really appreciate your software, especially tft_espi (very fast, only one that supports parallel, I've even taken first steps to expose it to micropython). But given that nothing worked, I eventually moved to JPEGDEC.

**Comment by Bodmer** [comment]
Post an example image that fails.

**Comment by Bodmer** [comment]
I have upgraded the library master to use the [latest decoder engine](http://elm-chan.org/fsw/tjpgd/00index.html). However the decoding process has not changed significantly. Also check your compiler optimisation settings are not having an effect, I tend to use Os as the optimisation level.

**Comment by boroncsokb** [comment]
Hi @Bodmer,

I am also having the same issue as described above. Everything worked great until I moved from Platformio to esp-idf (v4.4, using c++), but now I can not get it to work properly. The TFT_eSPI library still works, I can fill the screen with different colors, I can draw shapes on it without any problem, and also the TFT_Flash_Bitmap example works as intended, so I assume, that the communication with the screen is not the root cause.

However as I try to run the Flash_Jpg example from the TJpg_Decoder library (only switching the setup-loop functions to app_main for it to work in esp-idf), the image does not appear properly (see attached photo) 
On the serial output, it also says: "Width = 240, height = 0"
I have already tried setting the SwapBypes to true and false, but I get the same noisy image every time.

Do you have an idea, what could go wrong?

Thank you!
![IMG_20230329_224536](https://user-images.githubusercontent.com/39729562/228663452-0755f4e4-5dc6-40a6-b51a-147baac1c689.jpg)
