### ISSUE TITLE
"undefined reference to `BYTECLIP'"

### ISSUE THREAD

**Issue by sgrizzi** [Bodmer/TJpg_Decoder#41]
Hi, I am compiling the same project described by Jokikill at the beginning of this issue trail.
I am using Platformio, with the latest Espressif 32 platform 4.4.0 and I get the very same error "undefined reference to `BYTECLIP'" at the end of the linking process.
The board is the AI Thinker ESP32-CAM.
Any suggestion on how to solve the problem?
Thanks!

```
/Users/gabriele/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32cam/libd91/libTJpg_Decoder.a(tjpgd.c.o):(.literal.jd_decomp+0x18): undefined reference to `BYTECLIP'
/Users/gabriele/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32cam/libd91/libTJpg_Decoder.a(tjpgd.c.o): in function `block_idct':
/Users/gabriele/Documents/PlatformIO/Projects/esp32cam TFT/.pio/libdeps/esp32cam/TJpg_Decoder/src/tjpgd.c:1435: undefined reference to `BYTECLIP'
/Users/gabriele/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /Users/gabriele/Documents/PlatformIO/Projects/esp32cam TFT/.pio/libdeps/esp32cam/TJpg_Decoder/src/tjpgd.c:1436: undefined reference to `BYTECLIP'
/Users/gabriele/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /Users/gabriele/Documents/PlatformIO/Projects/esp32cam TFT/.pio/libdeps/esp32cam/TJpg_Decoder/src/tjpgd.c:1437: undefined reference to `BYTECLIP'
/Users/gabriele/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /Users/gabriele/Documents/PlatformIO/Projects/esp32cam TFT/.pio/libdeps/esp32cam/TJpg_Decoder/src/tjpgd.c:1438: undefined reference to `BYTECLIP'
/Users/gabriele/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/esp32cam/libd91/libTJpg_Decoder.a(tjpgd.c.o):/Users/gabriele/Documents/PlatformIO/Projects/esp32cam TFT/.pio/libdeps/esp32cam/TJpg_Decoder/src/tjpgd.c:1439: more undefined references to `BYTECLIP' follow
collect2: error: ld returned 1 exit status
*** [.pio/build/esp32cam/firmware.elf] Error 1
```

_Originally posted by @sgrizzi in https://github.com/Bodmer/TJpg_Decoder/issues/29#issuecomment-1144149747_

**Comment by Bodmer** [comment]
V1.0.5 is the latest on Github. Is that the version you are using.

**Comment by sgrizzi** [comment]
WOW. Platformio installed 0.2.0 by default and does not indicate that any update is available.
Thanks. I will somehow "force" downloading the newer library.

**Comment by sgrizzi** [comment]
If I try and "force" update to 1.0.5 I get this strange error....
```
Library Manager: Installing bodmer/TJpg_Decoder @ ^1.0.5
Error: Could not find the package with 'bodmer/TJpg_Decoder @ ^1.0.5' requirements for your system 'darwin_x86_64'
The terminal process "platformio 'run'" terminated with exit code: 1.
```
I have been running Platformio on my Mac for a few years now, and I am using it regularly to compile and run ESP32 code.
Platformio core is 6.0.2 and the espressif 32 platform is 4.4.0 - should both be up to date...
Do you have any idea on why I chould be getting this error? No problem if I move back to TJpg_Decoder @ ^0.2.0... weird

**Comment by Bodmer** [comment]
I have created a release version of 1.0.5 so that should be available when the PlatformIO next updates the links.

**Comment by ifengchao** [comment]
Hi Bodmer, still could not upgrade form pio IDE, the default version is 0.2.0 released a year ago, hope you can check that.

**Comment by pipi61** [comment]
try change
static uint8_t BYTECLIP (int val)
to
uint8_t BYTECLIP (int val)
in tjpgd.c

**Comment by Bodmer** [comment]
@pipi61 Thanks for the suggestion. I don't see the error myself so I am unable to check the "undefined problem" goes away. This problem seems to be specific to compilations under PlatformIO which is not an IDE I have used other than to try it a long time ago.

Te code section that generates the error was [coded by ChaN](http://elm-chan.org/fsw/tjpgd/00index.html) and it seems to compile fine under the Arduino IDE.

PlatformIO used to fetch the latest version but at some point during a platformIO services upgrade this stopped working.  Posts on the [PlatformIO forum](https://community.platformio.org/t/library-update-not-picked-up-by-platformio-org/1294/20?page=2) indicate there are other libraries that are not being seen as updated as well that have required action by the PlatformIO team.

**Comment by afteraincc** [comment]
BYTECLIP is a inline function.
the root cause is compiler, refer to [[STSTM32 build_flags break ‘inline’ keyword](https://community.platformio.org/t/ststm32-build-flags-break-inline-keyword-debug-build-flags-breaks-debugging/15296)](https://community.platformio.org/t/ststm32-build-flags-break-inline-keyword-debug-build-flags-breaks-debugging/15296).

**Comment by pipi61** [comment]
https://github.com/Bodmer/TJpg_Decoder/blob/master/src/tjpgd.c
here static...

**Comment by afteraincc** [comment]
> https://github.com/Bodmer/TJpg_Decoder/blob/master/src/tjpgd.c
> here static...
sorry, forgot some info.
Code of "Platformio installed 0.2.0 by default" is  an inline function, So it can't compile successfully.
I installed code of 1.0.5 version manually( ${ProjectPath}/lib/TJpg_Decoder ), It works.

**Comment by Bodmer** [comment]
OK, that explains it, thanks everyone.

**Comment by Bodmer** [comment]
I've tried bumping the version several times, but the registry does not pick this up. Also raised it on the PlatformIO forum but got no repsonse. Looks like others have had the same problem in the past and this needed action from the PlatformIO team.

So it seems the problem is at the PlatformIO end. Not sure who to prompt on this :-(

**Comment by hiibrarahmad** [comment]
![image](https://user-images.githubusercontent.com/46841978/216772412-4c5971d2-3571-42df-a46c-b9c18c133560.png)


still facing this isuue

**Comment by maxgerhardt** [comment]
But it goes away when you use 
```ini
lib_deps = 
   https://github.com/Bodmer/TJpg_Decoder.git
```
ni your `platformio.ini`?

**Comment by hiibrarahmad** [comment]
> But it goes away when you use
> 
> ```ini
> lib_deps = 
>    https://github.com/Bodmer/TJpg_Decoder.git
> ```
> 
> ni your `platformio.ini`?

yes it work

**Comment by ivankravets** [comment]
@Bodmer, sorry for the issue. Currently, PlatformIO uses legacy mode to fetch updates automatically for this library. We plan to remove it soon and highly recommend managing your updates manually using [this guide](https://docs.platformio.org/en/latest/librarymanager/creating.html). 

Regarding this issue. I've just checked it and I don't see any problems on the PlatformIO side. The library is linked to https://raw.githubusercontent.com/Bodmer/TJpg_Decoder/master/library.json manifest which points to the unknown `1.0.9` version (there is no `1.0.9` or `v1.0.9` tag). Typically, we increment the version before making a release/tag.

The solution to this issue is one of:

1. Revert back https://github.com/Bodmer/TJpg_Decoder/blob/master/library.json#L3 to `"version": "1.0.8"`, the same for `library.properties`. Versions should be the same in both manifests.
2. Download ZIP of 1.0.8 from https://github.com/Bodmer/TJpg_Decoder/releases/tag/v1.0.8 and type `pio pkg publish path/to/zip`. See [Publishing](https://docs.platformio.org/en/latest/librarymanager/creating.html#publishing) instruction.
 
The 2nd option with the RECOMMENDED solution. Library maintainers should personally decide which SOURCE and VERSION they want to publish to the registry. This is the answer to why we plan soon to stop "automatic fetching" to avoid similar issues.

Happy coding with PlatformIO!

**Comment by Bodmer** [comment]
@ivankravets The released version is v1.0.8, the latest master is 1.0.9 but has not been released yet so it is not clear what to do!

I use the Arduino IDE, not PlatformIO so I assume I will not be able to publish libraries to the PlatformIO registry :-(

**Comment by Bodmer** [comment]
Looks like latformIO just does not see the latest versions after 0.2.0:

![image](https://user-images.githubusercontent.com/15824805/216792853-ca9e9dae-3b2e-4b10-bdfb-0f26266e2f95.png)

**Comment by ivankravets** [comment]
I'm not sure that I understand the versioning policy in this repository. If you mean `master == release` following [git-flow](http://danielkummer.github.io/git-flow-cheatsheet/) branching model, then the `version` field in this branch should equal to the latest release. In this case, the `develop` branch should be used instead for trunk/upstream development where you can use pre-release version tags (`1.0.9-beta.1`, etc). If you have this, we can point the PlatformIO legacy crawler to the `library.json` located in the `master` branch which always follows the latest release. 

In the current situation, we instructed PlatformIO to use "tagged" branch https://raw.githubusercontent.com/Bodmer/TJpg_Decoder/v1.0.8/library.json
If you release the new version of this library, we will need to update this manifest URL.

So, anyone who uses this library with PlatformIO and sees that it is outdated in the PlatformIO Registry https://registry.platformio.org/libraries/bodmer/TJpg_Decoder, please ping me here. We will manually trigger the "updating" process while the author can't maintain this library himself.

P.S.: The new 1.0.8 is available in the registry. Happy coding with PlatformIO!

**Comment by Bodmer** [comment]
Thanks.
