### ISSUE TITLE
Official RP2040 MBed support?

### ISSUE THREAD

**Issue by IAmOrion** [Bodmer/TJpg_Decoder#54]
What's the chances this will eventually be able to support the Official RP2040 MBed boards instead of earlephilhower's ?

My project uses USBHID which earlephilhower does not support (Well, there's the confusing Adafruit TinyUSB I just discovered, but that seems messy), but I also want to use images in .h files using this TJpg_Decoder but apparently it doesn't work with the default RP2040 board selection

I'm buggered no matter what ha!

**Comment by Bodmer** [comment]
The library has worked with the Arduino mbed RP2040 package in the past with the exception that LittleFS, DMA and PIO could be used. Some examples worked fine. I have not checked for compatibility recently since Phil's package works so well. I have only used keyboard USB HID with Phil's package though.

**Comment by Bodmer** [comment]
I have updated the library and tested the Flash_Jpg example with TFT_eSPI and the RP2040 Mbed board package 3.4.1. It compiles fine after a few tweaks, see below.

You will need to comment out line 2 in User_Config.h that loads FLASH filing system support, See here:
https://github.com/Bodmer/TJpg_Decoder/blob/master/src/User_Config.h#L2

You may also need to comment out lines thus //#include <pgmspace.h> in a sketch because the Mbed package does not seem to provide that header. It would be nice to automate these things but I cannot see a way of idenitfying which board package is being used... maybe there is a package signature macro that I have not noticed?

**Comment by Bodmer** [comment]
I have made another change so User_Config.h does not need to be eddited.

**Comment by IAmOrion** [comment]
Interesting... did you change anything else? I changed the user_config same as here: https://github.com/Bodmer/TJpg_Decoder/commit/41aaa5361a3a3e07730f46f27d13419e008a8a42

But I get an error as FS.h being missing
